#!/usr/bin/env bash
# Tier 2 / connect end-to-end pairing
#
# Drives the bring-your-own-token path:
#   1. Run /cos-bot:connect interactively via pty-drive.py
#      Answers: paste token → authorize tmux+skip-permissions launch
#   2. Wait for bot to print "Listening..."
#   3. From host's TEST_CHAT_ID, send the pair code that connect just minted
#   4. Wait for "Paired!" to appear in the bot pane
#   5. Verify access.json has TEST_SENDER_ID in allowFrom
#
# Heavier than the demo round-trip — requires real-pty interactive
# claude. Container mode only.

set -euo pipefail

DRIVER_DIR="$(cd "$(dirname "$0")" && pwd)"
HARNESS_ROOT="$(cd "$DRIVER_DIR/../.." && pwd)"
ANSWERS="${ANSWERS:-$HARNESS_ROOT/fixtures/canned-answers/connect-bring-token.json}"

# shellcheck source=../../lib/sandbox.sh
source "$HARNESS_ROOT/lib/sandbox.sh"
# shellcheck source=../../lib/assert.sh
source "$HARNESS_ROOT/lib/assert.sh"
# shellcheck source=../../lib/bot-api.sh
source "$HARNESS_ROOT/lib/bot-api.sh"

if [[ "$IN_CONTAINER" = "0" ]]; then
  echo "[connect-pair] container only" >&2
  exit 2
fi

: "${TEST_BOT_TOKEN:?required for Tier 2}"
: "${TEST_CHAT_ID:?required for Tier 2}"
: "${TEST_SENDER_ID:?required for Tier 2}"

parse_keep_flag "$@"
mk_sandbox
install_local_plugin

# Answers config — fill in the actual TEST_BOT_TOKEN at runtime since
# canned-answers.json is checked in.
RUNTIME_ANSWERS="$REPORT_DIR/answers.json"
jq --arg token "$TEST_BOT_TOKEN" \
   '(.answers[] | select(.match | contains("Paste your token")) | .send) |= ($token + "\r")' \
   "$ANSWERS" > "$RUNTIME_ANSWERS"

(
  cd "$PROJECT_DIR"
  CLAUDE_CODE_OAUTH_TOKEN="$CLAUDE_CODE_OAUTH_TOKEN" \
    python3 "$HARNESS_ROOT/lib/pty-drive.py" \
      --config "$RUNTIME_ANSWERS" \
      --output "$REPORT_DIR/pty.log" \
      -- claude --permission-mode bypassPermissions
) || _assert_record FAIL "pty-drive failed (see $REPORT_DIR/pty.log)"

# After connect runs, we expect:
#   - ~/.claude/channels/telegram/.env has the token
#   - tmux session cos-bot exists (connect launched it)
#   - access.json *eventually* has TEST_SENDER_ID after pairing

assert_file_exists "$HOME/.claude/channels/telegram/.env"
assert_file_contains "$HOME/.claude/channels/telegram/.env" "$TEST_BOT_TOKEN"

if tmux has-session -t cos-bot 2>/dev/null; then
  _assert_record PASS "connect launched tmux session 'cos-bot'"
else
  _assert_record FAIL "no tmux 'cos-bot' session after connect"
fi

# Send the pair message from the test chat to trigger pairing.
# (Pair code is generated by the bot at first DM; we just need to talk
# to the bot at all.)
echo "[connect-pair] sending /start via Bot API to initiate pairing"
bot_drain_updates
bot_send_message "/start" > "$REPORT_DIR/pair-trigger.json"

# Wait for pairing to land.
deadline=$(( $(date +%s) + 90 ))
paired=0
while (( $(date +%s) < deadline )); do
  if [[ -f "$HOME/.claude/channels/telegram/access.json" ]]; then
    if jq -e --arg s "$TEST_SENDER_ID" '.allowFrom // [] | index($s)' \
       "$HOME/.claude/channels/telegram/access.json" >/dev/null 2>&1; then
      paired=1
      break
    fi
  fi
  sleep 2
done

if [[ "$paired" = "1" ]]; then
  _assert_record PASS "test sender paired in access.json"
else
  _assert_record FAIL "pairing didn't complete within 90s"
  cat "$HOME/.claude/channels/telegram/access.json" 2>/dev/null \
    > "$REPORT_DIR/access-final.json" || true
fi

tmux kill-session -t cos-bot 2>/dev/null || true

assert_summary
status=$?
teardown
exit $status
